### ISSUE TITLE
kapt dependency versions have to be specified explicitely

### ISSUE THREAD

**Issue by jsiefers** [Kiskae/androidx-bom#119]
Project does not build when I don't specify the version for kapt dependencies explicitely. For example, the setup below does not work:

```
implementation platform("net.serverpeon.androidx:androidx-bom:2020.02.12")
implementation 'androidx.appcompat:appcompat'
// ...
implementation "androidx.room:room-runtime"
kapt "androidx.room:room-compiler"
```

Whereas the following does work:

```
implementation platform("net.serverpeon.androidx:androidx-bom:2020.02.12")
implementation 'androidx.appcompat:appcompat'
// ...
implementation "androidx.room:room-runtime"
kapt "androidx.room:room-compiler:2.2.5"
```

The error I get when building the project in the first situation is the following (note that a gradle sync works without issue)

```
Could not find androidx.room:room-compiler:.
Searched in the following locations:
  - file:/path/to/my-project/app/libs/room-compiler.jar
Required by:
    project :app
```

**Comment by Kiskae** [comment]
It doesn't work because the `kapt` configuration does not depend on the `implementation` configuration. Because of this the platform dependency isn't visible while it is resolving the `kapt` dependencies.

It could be solved by either:
1. Adding the `platform` dependency to all the required configurations. 
`kapt platform("net.serverpeon.androidx:androidx-bom:2020.02.12")`
2. Create a seperate configuration to hold the platform and have all required configurations depend on that new configuration.
```
/* new versions configuration */
kapt dependsOn versions
implementation dependsOn versions
versions platform("net.serverpeon.androidx:androidx-bom:2020.02.12")
```
